# Workflow name
name: Docker Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'README.md'

# Just one job at this time
jobs:

  # Job name
  Job-Docker-Build:

    # Github Action runner
    runs-on: ubuntu-latest

    # Tasks
    steps:
      - name: Checkout repository as working directory
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set tag var
        id: tag
        run: |
          SHORT_SHA=$(git log --format="%H" -n 1 | cut -c1-7)
          TAG=$(date -u +${SHORT_SHA}-%Y%m%dT%H%M)
          echo "::set-output name=value::${TAG}"

      - name: Docker build and push
        uses: docker/build-push-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          push: true
          tags: webera/${{ github.event.repository.name }}:latest,webera/${{ github.event.repository.name }}:${{ steps.tag.outputs.value }}
